// // -----------------------------Start: 52_1 ---------------------------------------
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "./components/Navbar";
// import Footer from "./components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
      
//       <body className="min-h-full flex flex-col">
//         {/* (3)then in Navbar.jsx file */}
//         <Navbar/>
//         {children}
//         {/* (5) then go to page.js file */}
//         <Footer/>
//       </body>
//     </html>
//   );
// }
// // ---------------------End:52_1-(1) to () --------------------------------
// -----------------------------Start: 52_5 ---------------------------------------
// import { Geist, Geist_Mono } from "next/font/google";
// (1)
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
// (3)st commit previous
const josefin = Josefin_Sans({
  // variable: "--font-geist-sans",
  subsets: ["latin"],
});
// (3)en



// (2)commit it
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      // (4) then go to DestinationCard.jsx file
      className={`${josefin.className} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">
        
        <Navbar/>
        <Toaster />
        {children}
        
        <Footer/>
      </body>
    </html>
  );
}
// ---------------------End:52_5-(1) to () --------------------------------
